[project]
name = "technical-indicators"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "loguru>=0.7.3",
    "numpy>=2.2.4",
    "pydantic-settings>=2.6.1",
    "quixstreams>=3.11.0",
    "ta-lib>=0.6.3",
]
